config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'signup/successful' , to: 'signups#successful'
  post 'signup/sms_confirmation_certify' , to: 'signups#sms_confirmation_certify'
  patch 'signup/address/create' , to: 'signups#address_create'
  get 'signup/sms_confirmation' , to: 'signups#sms_confirmation_send'
  get 'signup/address' , to: 'signups#address'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'products/search_category' , to: 'products#search_category'
  get 'products/auto_complete' , to: 'products#auto_complete'
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signup#sms_confirmation_send'
  end
  root 'top#index'
  resources :top, only: :index
  resources :products, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get 'search', to: 'products#search_products'
    end
    resources :purchases, only: :new do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'address', to: 'purchases#address'
        get 'card', to: 'purchases#card'
        get 'card_index', to: 'purchases#card_index'
      end
    end
  end

  get 'mypage', to: 'users#show'
  resources :users, only: :new do
    resources :cards, only: [:index, :new, :destroy] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :new
  end
  resources :categories, only: :index
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  layout 'application-off-header-footer'

  def sms_confirmation_send
    @profile = Profile.new
    flash.delete(:notice)
  end

  def sms_confirmation_certify
    @profile = current_user.profile.assign_attributes(profile_params)
    if current_user.profile.valid?(:sms_confirmation_send)
      current_user.profile.update(profile_params)
    else
      @profile = Profile.new
      @errors = '未記入箇所があります'
      render 'sms_confirmation_send'
    end
  end

  def address
    
  end
  
  def oauth_google
    @user = User.new
    @user.email = session["devise.google_data"]["info"]["unverified_email"]
    @profile = @user.build_profile
  end
  
  def oauth_facebook
    @user = User.new
    @user.email = session["devise.facebook_data"]['info']['email']
    @profile = @user.build_profile
  end

  def address_create
    @profile = current_user.profile.assign_attributes(profile_params)
    if current_user.profile.valid?(:hoge)
      current_user.profile.update(profile_params)
    else
      @profile = current_user.profile
      @errors = '未記入箇所があります'
      render 'address' and return
    end
    case params[:move_from]
      when 'signup'
        redirect_to new_user_card_path(current_user.id)
      when 'purchase'
        redirect_to new_product_purchase_path(params[:product_id])
    end
  end

  def index
    
  end

  def new

  end
  def show

  end
  def successful

  end

  private

  def profile_params
    params.require(:profile).permit(:phone_number, :family_name, :last_name, :family_name_kana, :last_name_kana, :zipcode, :address_prefecture, :address_city, :address_street_number,:address_building_name)
  end

  def use_check_address_nil?
    false
  end
end

app/views/signups/_address.html.haml
.delivery
  = form_for(current_user.profile, url: signup_address_create_path) do |f|
    .delivery__title
      %h2 発送元・お届け先住所入力
      .signup-errors
        = @errors
      .delivery__info-container
        %ul
          %li
            %h3 お名前
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name,{class: 'text_field', placeholder: "例) 山田"}
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 彩"}
          %li
            %h3 お名前カナ
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name_kana,{class: 'text_field', placeholder: "例) ヤマダ"}
          = f.text_field :last_name_kana,{class: 'text_field', placeholder: "例) アヤ"}
          %li
            %h3 郵便番号
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :zipcode,{class: 'text_field', placeholder: "例) 123-4567"}
          %li
            %h3 都道府県
          %li
            .required__icon 必須
          .clearfix
            .input-append
              .select-tag
                = f.collection_select( :address_prefecture, Prefecture.all, :id, :name)
            = fa_icon 'chevron-down', class: 'fa-icon_4'
          %li
            %h3 市町村
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :address_city,{class: 'text_field', placeholder: '例) 横浜市緑区'}
          %li
            %h3 番地
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :address_street_number,{class: 'text_field', placeholder: '例) 青山1-1-1'}
          %li
            %h3 建物名
          %li
            .required__icon 任意
          .clearfix
          = f.text_field :address_building_name,{class: 'text_field', placeholder: '例) 柳ビル103'}
          %li
            %h3 電話
          %li
            .required__icon 任意
          .clearfix
          = f.text_field :phone_number,{class: 'text_field', placeholder: '例) 09012345678'}
          %input{type: 'hidden', name: 'move_from', value: move_from}
          - case local_assigns[:move_from]
            - when 'signup'
              = f.submit '次へ進む', id: 'token_submit', class:'next_btn'
            - when 'purchase'
              %input{type: 'hidden', name: 'product_id', value: product_id}
              = f.submit '変更する', id: 'token_submit', class:'next_btn'
          .clearfix

app/views/signups/address.html.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header3.png',size: "720x110" , class: "header__bar-img"
= render partial: 'address', locals: { move_from: 'signup' }
= render partial:'products/product_footer'

app/views/signups/index.html.haml
%header
  = link_to(root_path) do
    = image_tag 'mercari_logo_horizontal.png',size: "234x76" , class: "header__logo-img_signup"
  = image_tag 'signup_header1.png',size: "670x103" , class: "header__bar-img"
.sigup
  .sigup__title
    %h2 会員情報入力
    .sigup__info-container
      %ul
        %li
          %h3 ニックネーム
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '例) メルカリ太郎',class: 'text_field'
        %li
          %h3 メールアドレス
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, 'PC・携帯どちらでも可',class: 'text_field'
        %li
          %h3 パスワード
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '6文字以上',class: 'text_field'
        %li
          %h3 パスワード（確認）
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '6文字以上',class: 'text_field'
        %li
          %h3 本人確認
        .clearfix
        %li
          %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        .clearfix
        %li
          %h3 姓（全角）
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '例) 山田',class: 'text_field'
        %li
          %h3 名（全角）
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '例) 彩',class: 'text_field'
        %li
          %h3 姓カナ（全角)
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '例) ヤマダ',class: 'text_field'
        %li
          %h3 名カナ（全角）
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '例) アヤ',class: 'text_field'
        %li
          %h3 生年月日
        %li
          .required__icon 必須
        .clearfix
        = date_select :page, :updated_at,class: 'select', use_month_numbers: true, discard_month: true, discard_day: true, start_year: 1900
        = fa_icon 'chevron-down', class:'fa_icon_1'
        %sub.left 年
        = date_select :page, :updated_at,class: 'select', use_month_numbers: true, discard_year: true, discard_day: true
        = fa_icon 'chevron-down', class:'fa_icon_2'
        %sub.left 月
        = select_tag 'category', options_for_select({'01':'01','02':'02','03':'03','04':'04','05':'05','06':'06','07':'07','08':'08','09':'09','10':'10','11':'11','12':'12','13':'13','14':'14','15':'15','16':'16','17':'17','18':'18','19':'19','20':'20','21':'21','22':'22','23':'23','24':'24','25':'25','26':'26','27':'27','28':'28','29':'29','30':'30','31':'31'}),class: 'select_tag_left'
        = fa_icon 'chevron-down', class:'fa_icon_3'
        %sub.left 日
        .clearfix
        .dscription
          %p.gray ※本人情報は正しく入力してください。会員登録後、修正するにはお時間をいただく場合があります。
        = image_tag 'rbot-img.png',size: "325x90" , class: "rbot-img"
        .dscription
          %p「次へ進む」のボタンを押すことにより、
          %p.blue 利用規約
          %p に同意したものとみなします。
        .next-btn
          = link_to "次へ進む","/users/1/signups/new", class:'next_btn'
          -#### 仮置き。サーバサイド実装後、/users/:user_id/signups/newに修正
        .link-box
          %li
            %p 本人情報の登録について
          %li
            = fa_icon 'chevron-right', class:'arrow_blue'
        .clearfix

= render partial:'products/product_footer'

app/views/signups/oauth_facebook.html.haml
%header
  = link_to(root_path) do
    = image_tag "mercari_logo_horizontal.png", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header1.png',size: "670x103" , class: "header__bar-img"
.sigup
  = form_for(@user, url: user_registration_path ) do |f|

    .sigup__title
      %h2 会員情報入力
    .signup-errors
      = @errors
    .sigup__info-container
      %ul
        %li
          %h3 ニックネーム
        %li
          .required__icon 必須
        .clearfix
        = f.text_field :nickname,{ autofocus: true ,class: 'text_field', placeholder: "例) メルカリ太郎",autocomplete: "off"}
        %li
          %h3 メールアドレス
        %li
          .required__icon 必須
        .clearfix
        = f.email_field :email,{ class: 'text_field', placeholder: "PC・携帯どちらでも可"}
        -if session["devise.facebook_data"]
          = f.hidden_field :password, value: Devise.friendly_token[0,20]
          = f.hidden_field :password_confirmation, value: Devise.friendly_token[0,20]
        %li
          %h3 本人確認
        .clearfix
        %li
          %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        = f.fields_for :profile do |f|
          .clearfix
          %li
            %h3 姓（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name,{class: 'text_field', placeholder: "例) 山田"}
          %li
            %h3 名（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 彩"}
          %li
            %h3 姓カナ（全角)
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name_kana,{class: 'text_field', placeholder: "例) ヤマダ"}
          %li
            %h3 名カナ（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name_kana,{class: 'text_field', placeholder: "例) アヤ"}
          %li
            %h3 生年月日
          %li
            .required__icon 必須
          .clearfix
          = f.date_select( :birth_ymd, use_month_numbers: true, prompt:  '　　---',start_year: 1930, end_year: (Time.now.year - 18), blank:'---',default: Date.new(1989, 1, 1), id:'page_updated_at_1i')
          .clearfix
          .dscription
            %p.gray ※本人情報は正しく入力してください。会員登録後、修正するにはお時間をいただく場合があります。
          = recaptcha_tags
          .dscription
            %p「次へ進む」のボタンを押すことにより、
            %p.blue 利用規約
            %p に同意したものとみなします。
          .next-btn
            = f.submit('次へ進む' ,class:'redbtn')
          .link-box
            %li
              %p 本人情報の登録について
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'products/product_footer'

app/views/signups/oauth_google.html.haml
%header
  = link_to(root_path) do
    = image_tag "mercari_logo_horizontal.png", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header1.png',size: "670x103" , class: "header__bar-img"
.sigup
  = form_for(@user, url: user_registration_path ) do |f|

    .sigup__title
      %h2 会員情報入力
    .signup-errors
      = @errors
    .sigup__info-container
      %ul
        %li
          %h3 ニックネーム
        %li
          .required__icon 必須
        .clearfix
        = f.text_field :nickname,{ autofocus: true ,class: 'text_field', placeholder: "例) メルカリ太郎",autocomplete: "off"}
        %li
          %h3 メールアドレス
        %li
          .required__icon 必須
        .clearfix
        = f.email_field :email,{ class: 'text_field', placeholder: "PC・携帯どちらでも可"}
        -if session["devise.google_data"]
          = f.hidden_field :password, value: password=Devise.friendly_token[0,20]
          = f.hidden_field :password_confirmation, value: password
        %li
          %h3 本人確認
        .clearfix
        %li
          %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        = f.fields_for :profile do |f|
          .clearfix
          %li
            %h3 姓（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name,{class: 'text_field', placeholder: "例) 山田"}
          %li
            %h3 名（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 彩"}
          %li
            %h3 姓カナ（全角)
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name_kana,{class: 'text_field', placeholder: "例) ヤマダ"}
          %li
            %h3 名カナ（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name_kana,{class: 'text_field', placeholder: "例) アヤ"}
          %li
            %h3 生年月日
          %li
            .required__icon 必須
          .clearfix
          = f.date_select( :birth_ymd, use_month_numbers: true, prompt:  '　　---',start_year: 1930, end_year: (Time.now.year - 18), blank:'---',default: Date.new(1989, 1, 1), id:'page_updated_at_1i')
          .clearfix
          .dscription
            %p.gray ※本人情報は正しく入力してください。会員登録後、修正するにはお時間をいただく場合があります。
          = recaptcha_tags
          .dscription
            %p「次へ進む」のボタンを押すことにより、
            %p.blue 利用規約
            %p に同意したものとみなします。
          .next-btn
            = f.submit('次へ進む' ,class:'redbtn')
          .link-box
            %li
              %p 本人情報の登録について
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'products/product_footer'

app/views/signups/sms_confirmation_certify.html.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header2.png',size: "700x120" , class: "header__bar-img"
.sigup_sms-2
  .sigup__title
    %h2 電話番号認証
    .signup-errors
      = @errors
    .sigup__info-container
      %ul
        %li
          %h3 認証番号
        .clearfix
        = text_field_tag :content, '',{ class: 'text_field', placeholder: "携帯電話の番号を入力"}
        .clearfix
        %li
          %p SMSで届いた認証番号を入力してください。
        .clearfix
        = link_to "認証して完了",signup_address_path, class:'sms-btn_2'
        .clearfix
    .sigup__info-box
    .sigup__info-box
      %h3 30秒たっても認証番号が届かない方へ
      %p 電話で認証番号を聞くこともできます。
      .clearfix
      .sms-btn_3
        = link_to "電話で認証番号を聞く（通話無料）", class:'sms-btn'
      .clearfix
    .sigup__info-box_2
      %h3 認証番号を再送することもできます。もう一度電話番号を入力してください。
      %p.blue  電話番号を再度入力する
      %br
      .dscription
        ※SMSが届かない場合は
        %span.blue SMS受信設定
        を確認して、もう一度電話番号を入力してください。
= render partial:'products/product_footer'

app/views/signups/sms_confirmation_send.html.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header2.png',size: "700x120" , class: "header__bar-img"
.sigup_sms
  = form_for(@profile, url: signup_sms_confirmation_certify_path) do |f|
    .sigup__title
      %h2 電話番号の確認
      .signup-errors
        = @errors
      .sigup__info-container
        %ul
          %li
            %h3 携帯電話の番号
          .clearfix
          = f.text_field :phone_number, { class: 'text_field', placeholder: "携帯電話の番号を入力"}
          .clearfix
          %li
            %p 本人確認のため、携帯電話番号のSMS (ショートメッセージサービス)を
            %p 利用して認証を行います。
          .clearfix
          = f.submit('SMSを送信する' ,class:'next_btn')
          .clearfix
            %br
            %p 電話番号は本人確認や不正利用防止のために利用します。
            %p 他のユーザーに公開されることはありません。
          .link-box
            %li
              %p 電話番号の確認が必要な理由
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'products/product_footer'

app/views/signups/successful.html.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header5.png',size: "680x90" , class: "header__bar-img"
.sigup-complete
  .sigup__title
    %h2 会員登録完了
    .sigup__info-container
      .description
        %span.thanks ありがとうございます。
        %br
        %span.complete 会員登録が完了しました。
        %br/
      .clearfix
    = link_to "メルカリをはじめる", mypage_path, class:'start-btn'
    .clearfix
    = image_tag 'register_complete_img.png',size: "800x300", class: "register_complete_img"
= render partial:'products/product_footer'