config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'signup/successful' , to: 'signups#successful'
  post 'signup/sms_confirmation_certify' , to: 'signups#sms_confirmation_certify'
  patch 'signup/address/create' , to: 'signups#address_create'
  get 'signup/sms_confirmation' , to: 'signups#sms_confirmation_send'
  get 'signup/address' , to: 'signups#address'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'products/search_category' , to: 'products#search_category'
  get 'products/auto_complete' , to: 'products#auto_complete'
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signup#sms_confirmation_send'
  end
  root 'top#index'
  resources :top, only: :index
  resources :products, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get 'search', to: 'products#search_products'
    end
    resources :purchases, only: :new do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'address', to: 'purchases#address'
        get 'card', to: 'purchases#card'
        get 'card_index', to: 'purchases#card_index'
      end
    end
  end

  get 'mypage', to: 'users#show'
  resources :users, only: :new do
    resources :cards, only: [:index, :new, :destroy] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :new
  end
  resources :categories, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile, dependent: :destroy
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  accepts_nested_attributes_for :profile
  
  has_one :card, dependent: :destroy

  has_many :buyed_deals, foreign_key: :buyer_id, class_name: :Deal
  has_many :selling_deals, -> { where("buyer_id is NULL") }, foreign_key: :seller_id, class_name: :Deal
  has_many :sold_deals, -> { where("buyer_id is not NULL") }, foreign_key: :seller_id, class_name: :Deal

  has_many :buyed_products, through: :buyed_deals, source: :product
  has_many :selling_products, through: :selling_deals, source: :product
  has_many :sold_products, through: :sold_deals, source: :product

  validates :nickname, presence: true, exclusion: { in: %w(メルカリ) }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, format: { with: /\A(?=.*?[a-z])[a-z\d]+\z/i }
  validates :password_confirmation, presence: true, length: { minimum: 6 }

  def self.profile_nested_with_user_is_valid?(params)
    params[:user][:profile_attributes][:family_name].present?\
    && params[:user][:profile_attributes][:last_name].present?\
    && params[:user][:profile_attributes][:family_name_kana].present?\
    && params[:user][:profile_attributes][:last_name_kana].present?\
    && params[:user][:profile_attributes][:'birth_ymd(1i)'].present?\
    && params[:user][:profile_attributes][:'birth_ymd(2i)'].present?\
    && params[:user][:profile_attributes][:'birth_ymd(3i)'].present?
  end
      # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    @credential = SnsCredential.where(provider: auth.provider, uid: auth.uid,email:auth.info.email).first_or_create
    @user = User.where(email:auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.password_confirmation = Devise.friendly_token[0,20]
    end
    @user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to "/signup/#{provider}"
    end
  end

  def failure
    redirect_to top_index_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :check_captcha, only: [:create]
  layout 'application-off-header-footer'

  def new
    @user = User.new
    @profile = @user.build_profile
    session["devise.facebook_data"] = nil
    session["devise.google_data"] = nil
  end

  def create
    if User.profile_nested_with_user_is_valid?(params)&&verify_recaptcha(model: resource)
       super and return
    else
      @user = build_resource(sign_up_params)
      @profile = @user.profile
      @errors='未記入箇所があります'
      render 'new' and return
    end
  end

  def after_sign_up_path_for(resource)
    signup_sms_confirmation_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'application-off-header-footer'
  prepend_before_action :confirm_recaptcha, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private

  def confirm_recaptcha
    unless verify_recaptcha(model: resource)
      self.resource = User.new
      render 'new' and return
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render layout: 'application-off-header-footer.html.haml'
  end

  def show
    @user = User.find(current_user.id)
  end
end

app/views/users/_user_side_menu.html.haml
.user_mypage__container__side
  .user_mypage__container__side__menu
    %ul.user_mypage__container__side__menu__list
      %li.user_mypage__container__side__menu__list__product
        = link_to mypage_path, class: 'user_mypage__container__side__menu__list__product__text-active' do
          マイページ
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          お知らせ
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          やることリスト
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          いいね！一覧
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to new_product_path, class: 'user_mypage__container__side__menu__list__product__text', data: {"turbolinks" => false} do
          出品する
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          ニュース一覧
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          評価一覧
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          ガイド
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          お問い合わせ
          %i.fas.fa-chevron-right

    %h3.user_mypage__container__side__menu__title メルペイ
    %ul.user_mypage__container__side__menu__list
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          売り上げ・振込申請
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          ポイント
          %i.fas.fa-chevron-right

    %h3.user_mypage__container__side__menu__title 設定
    %ul.user_mypage__container__side__menu__list
      %li.user_mypage__container__side__menu__list__product
        = link_to edit_user_user_profile_path(current_user, 1), class: 'user_mypage__container__side__menu__list__product__text' do
          プロフィール
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to user_cards_path(current_user), class: 'user_mypage__container__side__menu__list__product__text' do
          支払い方法
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          メール/パスワード
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to edit_user_user_confirmation_path(current_user, 1), class: 'user_mypage__container__side__menu__list__product__text' do
          本人情報
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to "#", class: 'user_mypage__container__side__menu__list__product__text' do
          電話番号の確認
          %i.fas.fa-chevron-right
      %li.user_mypage__container__side__menu__list__product
        = link_to new_user_logout_path(current_user), class: 'user_mypage__container__side__menu__list__product__text' do
          ログアウト
          %i.fas.fa-chevron-right

app/views/users/edit.html.haml
.user_mypage
  .user_mypage__container
    .user_mypage__container__edit
      .user_mypage__container__edit__title
        %h2 プロフィール
      .user_mypage__container__edit__editform
        .user_mypage__container__edit__editform__name
          %figure
            = image_tag "ねこ２.jpeg", width: "60", height: "60"
          %input{type: "text", name: "nickname", class: "user_mypage__container__edit__editform__name__inputbox"}
        .user_mypage__container__edit__editform__content
          %textarea{name: "profile_comment"}
          %button{type: "submit", class: "user_mypage__container__edit__editform__content__submit redbtn"} 変更する

    =render partial: "users/user_side_menu"

app/views/users/new.html.haml
%header
  = link_to(root_path) do
    = image_tag 'mercari_logo_horizontal.png',size: "234x76" , class: "header__logo-img"


.user
  .user__title
    %h2 新規会員登録
    .user__btn_container
      .user__btn_mail
        = fa_icon 'envelope', class:'mail-icon'
        = link_to "メールアドレスで登録", new_user_registration_path
      .user__btn_fb
        = image_tag 'facebook_icon.png',size: "35x35" , class: "facebook-icon"
        = link_to "Facebookで登録", user_facebook_omniauth_authorize_path, method: :post
      .user__btn_google
        = image_tag 'google_icon.png',size: "37x37" , class: "google-icon"
        = link_to "Googleで登録",user_google_oauth2_omniauth_authorize_path, method: :post

= render partial:'products/product_footer'

app/views/users/show.html.haml
- breadcrumb :mypage
.user_mypage
  .user_mypage__container
    .user_mypage__container__main
      -# ユーザー情報
      .user_mypage__container__main__user_info
        = link_to "#", class: 'user_mypage__container__main__user_info__link' do
          %figure
            -if current_user.profile.avatar.blank?
              = image_tag 'ねこ２.jpg', width: "60", height: "60"
            -else
              = image_tag current_user.profile.avatar.url, width: "60", height: "60"
          %h2.user_mypage__container__main__user_info__link__user-name
            - if @current_user.profile.nickname.blank?
              = @current_user.nickname
            - else
              = @current_user.profile.nickname
          .user_mypage__container__main__user_info__link__count
            .user_mypage__container__main__user_info__link__count__rating
              評価
              %span 6
            .user_mypage__container__main__user_info__link__count__listing
              出品数
              %span 13

      -# お知らせとやることリスト
      .user_mypage__container__main__notification_todo

        -# タブ(css)
        .user_mypage__container__main__notification_todo__tabs
          %input#information_tab{checked: "checked", name: "tab_product", type: "radio"}/
          %label.tab_product{for: "information_tab"} お知らせ

          %input#todo_tab{name: "tab_product", type: "radio"}/
          %label.tab_product{for: "todo_tab"} やることリスト

          #information_content.user_mypage__container__main__notification_todo__tabs__content
            %ul.user_mypage__container__main__notification_todo__tabs__content__list
              %li.user_mypage__container__main__notification_todo__tabs__content__list__product
                = link_to "#", class: 'user_mypage__container__main__notification_todo__tabs__content__list__product__link' do
                  %figure
                    =image_tag "mercari_icon.png", class: "user_mypage__container__main__notification_todo__tabs__content__list__product__link__icon"
                  .user_mypage__container__main__notification_todo__tabs__content__list__product__link__body
                    .user_mypage__container__main__notification_todo__tabs__content__list__product__link__body__text テキスト
                    %time
                      %i.far.fa-clock
                      %span ２０時間前
                  %i.fas.fa-chevron-right

              %li.user_mypage__container__main__notification_todo__tabs__content__list__product
                = link_to "#", class: 'user_mypage__container__main__notification_todo__tabs__content__list__product__link' do
                  %figure
                    =image_tag "mercari_icon.png", class: "user_mypage__container__main__notification_todo__tabs__content__list__product__link__icon"
                  .user_mypage__container__main__notification_todo__tabs__content__list__product__link__body
                    .user_mypage__container__main__notification_todo__tabs__content__list__product__link__body__text テキスト
                    %time
                      %i.far.fa-clock
                      %span ２０時間前
                  %i.fas.fa-chevron-right

              %li.user_mypage__container__main__notification_todo__tabs__content__list__go-list
                = link_to "#", class: 'user_mypage__container__main__notification_todo__tabs__content__list__go-list__link' do
                  一覧を見る

          #todo_content.user_mypage__container__main__notification_todo__tabs__content
            .user_mypage__container__main__notification_todo__tabs__content__todo_list
              %p 現在やることはありません

      -# 購入した商品
      .user_mypage__container__main__buyed_products
        %h2.user_mypage__container__main__buyed_products__title
          購入した商品
        -# タブ(js)
        .user_mypage__container__main__buyed_products__tabs
          %a.user_mypage__container__main__buyed_products__tabs__btn
            取引中
          %a.user_mypage__container__main__buyed_products__tabs__btn
            過去の取引

          .user_mypage__container__main__buyed_products__tabs__content
            取引中の商品がありません
          .user_mypage__container__main__buyed_products__tabs__content
            過去に取引した商品がありません

          -# タブ部分のjs
          %script{crossorigin: "anonymous", integrity: "sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=", src: "https://code.jquery.com/jquery-3.3.1.js"}
          :javascript
            $(document).on("turbolinks:load", function () {
              /*初期表示*/
              $('.user_mypage__container__main__buyed_products__tabs__content').hide();
              $('.user_mypage__container__main__buyed_products__tabs__content').eq(0).show();
              $('.user_mypage__container__main__buyed_products__tabs__btn').eq(0).addClass('is-active');
              /*クリックイベント*/
              $('.user_mypage__container__main__buyed_products__tabs__btn').each(function () {
                $(this).on('click', function () {
                  var index = $('.user_mypage__container__main__buyed_products__tabs__btn').index(this);
                  $('.user_mypage__container__main__buyed_products__tabs__btn').removeClass('is-active');
                  $(this).addClass('is-active');
                  $('.user_mypage__container__main__buyed_products__tabs__content').hide();
                  $('.user_mypage__container__main__buyed_products__tabs__content').eq(index).show();
                });
              });
            });
    =render partial: "users/user_side_menu"

app/views/users/show2.html.haml
.zentai 
  .header
    = image_tag "logo.svg",  class: "image_sign_up"
    = image_tag 'signup_header2.png', class: "data__img"
  .contents
    .contents-box
      .contents-box__title
        %h 電話番号確認
      .contents-box__input
        .input-box
          .phone_number
            %label 携帯電話の電話番号
            %input{placeholder: "携帯の電話番号を入力"}
          %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          %button SMSを送信する
          %p.tyuui ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          %h1
          =link_to "電話番号の確認が必要な場合＞",color: "light-blue"
  = render partial:'footer'