config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'signup/successful' , to: 'signups#successful'
  post 'signup/sms_confirmation_certify' , to: 'signups#sms_confirmation_certify'
  patch 'signup/address/create' , to: 'signups#address_create'
  get 'signup/sms_confirmation' , to: 'signups#sms_confirmation_send'
  get 'signup/address' , to: 'signups#address'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'products/search_category' , to: 'products#search_category'
  get 'products/auto_complete' , to: 'products#auto_complete'
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signup#sms_confirmation_send'
  end
  root 'top#index'
  resources :top, only: :index
  resources :products, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get 'search', to: 'products#search_products'
    end
    resources :purchases, only: :new do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'address', to: 'purchases#address'
        get 'card', to: 'purchases#card'
        get 'card_index', to: 'purchases#card_index'
      end
    end
  end

  get 'mypage', to: 'users#show'
  resources :users, only: :new do
    resources :cards, only: [:index, :new, :destroy] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :new
  end
  resources :categories, only: :index
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product,only: [:new, :pay, :address, :card, :card_index]

  require 'payjp'
  require 'date'

  def new
    @card = current_user.card
    if @card 
      Payjp.api_key = Rails.application.credentials.payjp[:test_secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
    render layout: 'application-off-header-footer.html.haml'
  end

  def pay
    card = Card.find_by(user_id: current_user.id)
    deal = Deal.find_by(product_id: @product.id)
    if card
      Payjp.api_key = Rails.application.credentials.payjp[:test_secret_key]
      charge = Payjp::Charge.create(
        amount:   @product.price,
        customer: card.customer_id,
        currency: 'jpy',
      )
      deal.charge_id = charge.id
      deal.buyer_id = current_user.id
      deal.position_id = 2 # ステータスを取引中に更新
      deal.deal_at = DateTime.now
      deal.save
      flash[:notice] = '商品を購入しました'
      redirect_to controller: :users, action: :show, id: current_user.id
    else
      flash[:alert] = 'カード情報を登録してください'
      redirect_to controller: :purchases, action: :new, product_id: @product.id
    end
  end

  def address
    render layout: 'application-off-header-footer.html.haml'
  end

  def card
    gon.payjp_test_pk = Rails.application.credentials.payjp[:test_public_key]
    render layout: 'application-off-header-footer.html.haml'
  end

  def card_index
    @card = current_user.card
    if @card
      Payjp.api_key = Rails.application.credentials.payjp[:test_secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
    render layout: 'application-off-header-footer.html.haml'
  end
  
  private

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/views/purchases/address.html.haml
%header
  = link_to(root_path) do
    = image_tag 'mercari_logo_horizontal.png',size: "234x76" , class: "header__logo-img"
= render partial: 'signups/address', locals: { move_from: 'purchase' , product_id: @product.id}
= render partial:'products/product_footer'

app/views/purchases/card.html.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img"
.user_mypage
.user_mypage__container
  .credit_3
    .credit__title
      %h2 支払い方法
    = render partial:'cards/cards_detail', locals: { move_from_action: "purchase", product_id: @product.id }
= render partial:'products/product_footer'

app/views/purchases/card_index.html.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img"
.reposition-wrapper
.user_mypage
  .user_mypage__container
    = render partial: 'users/user_side_menu'
    = render partial: 'cards/cards_main_menu', locals: { move_from: 'purchase', product_id: @product.id }
    = render partial: 'products/product_footer'

app/views/purchases/new.html.haml
.product_wrapper
  %header
    = link_to (root_path) do
      = image_tag 'mercari_logo_horizontal.png',size: "234x76" , class: "header__logo-img"
  .product
    .product__title
      購入内容の確認
    .product__info
      .product__info__inner-content
        .product__info__inner-content__image
          = image_tag @product.product_images.first.image_url.to_s, height: '148', width: '148'
        .product__info__inner-content__name
          %p
            = @product.name
        .product__info__inner-content__subtotal
          .product__info__inner-content__subtotal__price
            %p
              = "¥ #{@product.price.to_s(:delimited)}"
          .product__info__inner-content__subtotal__delivery-fee
            %p
              = @product.shipping_fee_payer
        .product__info__inner-content__point
          ポイントはありません
        .product__info__inner-content__account
          .product__info__inner-content__account__text
            支払い金額
          .product__info__inner-content__account__price
            %p
              = "¥ #{(@product.price - 0).to_s(:delimited)}"
        = form_tag(pay_product_purchases_path(@product), method: :post) do
          = submit_tag "購入する", class: 'product__info__inner-content__purchase-btn'
    .product__address
      .product__address__inner-content
        .product__address__inner-content__heading
          配送先
        .product__address__inner-content__info
          .product__address__inner-content__info__text
            = "〒" + current_user.profile.zipcode
            %br
            = Prefecture.where(id: current_user.profile.address_prefecture)[0].attributes[:name]
            = current_user.profile.address_city
            = current_user.profile.address_street_number
            = current_user.profile.address_building_name
            %br
            = current_user.profile.family_name
            = current_user.profile.last_name
          = link_to address_product_purchases_path(@product) do
            .product__address__inner-content__info__fix
              変更する
            %i >
    .product__payment
      .product__payment__inner-content
        .product__payment__inner-content__heading
          支払い方法
        - if @default_card_information
          .product__payment__inner-content__info
            .product__payment__inner-content__info__text
              = "************" + @default_card_information.last4
              %br
              = get_card_exp(@default_card_information)
            .product__payment__inner-content__info__figure
              = get_cards_brand_logo(@default_card_information.brand)
          = link_to card_index_product_purchases_path(@product) do
            .product__payment__inner-content__info__fix
              変更する
              %i >
        - else
          = link_to card_product_purchases_path(@product), data: {turbolinks: false} do
            .product__payment__inner-content__info__fix
              追加する
              %i >
  = render 'products/product_footer'