config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'signup/successful' , to: 'signups#successful'
  post 'signup/sms_confirmation_certify' , to: 'signups#sms_confirmation_certify'
  patch 'signup/address/create' , to: 'signups#address_create'
  get 'signup/sms_confirmation' , to: 'signups#sms_confirmation_send'
  get 'signup/address' , to: 'signups#address'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'products/search_category' , to: 'products#search_category'
  get 'products/auto_complete' , to: 'products#auto_complete'
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signup#sms_confirmation_send'
  end
  root 'top#index'
  resources :top, only: :index
  resources :products, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get 'search', to: 'products#search_products'
    end
    resources :purchases, only: :new do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'address', to: 'purchases#address'
        get 'card', to: 'purchases#card'
        get 'card_index', to: 'purchases#card_index'
      end
    end
  end

  get 'mypage', to: 'users#show'
  resources :users, only: :new do
    resources :cards, only: [:index, :new, :destroy] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :new
  end
  resources :categories, only: :index
end

app/views/shared/_global-footer.html.haml
.app-banner
  .app-banner__box
    .app-banner__box__left
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner__box__left__icons
        = image_tag "app-banner-mercari-logo.png", width: "68", height: "68"  ,class:"mercari"
        = image_tag "banner-mercari-info-apple.svg", width: "128", height: "39"  ,class:"apple"
        = image_tag "banner-mercari-info-google-play.svg", width: "128", height: "39"  ,class:"google"
    .app-banner__box__right
      .app-banner__right__image
        = image_tag "app-banner-right.png", width: "300", height: "260"  ,class:"banner-mercari-info-hand-phone"
.global-footer
  .global-footer__upper
    .global-footer__upper__cell.about-mercari
      %h2 メルカリについて
      %ul
        %li= link_to '会社概要(運営会社)',"#"
        %li= link_to '採用情報',"#"
        %li= link_to 'プレスリリース',"#"
        %li= link_to '公式ブログ',"#"
        %li= link_to 'メルカリロゴ利用ガイドライン',"#"
      .global-footer__upper__cell__social-link
        %i.fab.fa-twitter
        &nbsp;  
        %i.fab.fa-facebook-square
    .global-footer__upper__cell.help-guide
      %h2 ヘルプ＆ガイド
      %ul
        %li= link_to 'メルカリガイド',"#"
        %li= link_to 'らくらくメルカリ便',"#"
        %li= link_to 'ゆうゆうメルカリ便',"#"
        %li= link_to '大型メルカリ便',"#"
        %li= link_to '車体取引ガイド',"#"
        %li= link_to 'メルカリあんしん・あんぜん宣言！',"#"
        %li= link_to '偽ブランド品撲滅への取り組み',"#"
        %li= link_to 'メルカリボックス',"#"
    .global-footer__upper__cell.privacy    
      .global-footer__upper__cell
        %h2 プライバシーと利用規約
        %ul
          %li= link_to 'プライバシーポリシー',"#"
          %li= link_to 'メルカリ利用規約',"#"
          %li= link_to 'あんしんスマホサポート制度に関する利用特約',"#"
          %li= link_to 'コンプライアンスポリシー',"#"
      .global-footer__upper__cell
        %h2  
          %br/
        %ul
          %li= link_to '個人データの安全管理に係る基本方針',"#"
          %li= link_to '特定商取引に関する表記',"#"
          %li= link_to '資金決済法に基づく表示',"#"
          %li= link_to '法令遵守と犯罪抑止のために',"#"
          %li= link_to '返品・返金ポリシー',"#"
    .global-footer__upper__cell.country
      %h2 国
      %ul
        %li= link_to '日本',"#"
        %li= link_to 'United States',"#"
  .global-footer__lower
    = image_tag "footer-white-logo.svg", width: "124", height: "33"  ,class:"google"
    .footer-copylight
      %small © 2019 Mercari
= render partial:'shared/global-sell-button'
= link_to(new_product_path, class:'footer-sell-button', data: {"turbolinks" => false}) do
  %h2 出品
  %i.fas.fa-camera

app/views/shared/_global-header.html.haml
.global-header
  .header
    .header-upper.clearfix
      .logo
        = link_to(root_path) do
          = image_tag "logo.svg", width:  "134", height: "36"
      = form_tag(search_products_path, method: :get, class: "form") do
        = text_field_tag :keyword, "", class: 'textbox', placeholder: '何かお探しですか？'
        .form__icon-search
          = button_tag type: "submit", class: "btn"  do
            %i.fa.fa-search
    .header-lower.clearfix
      .header-lower-left
        %ul.menu
          %li.menu__category-menu
            = link_to categories_path, class: 'menu__category-menu__button' do
              %i.fas.fa-list-ul
              カテゴリーから探す
            %ul.menu__main-level
              / 第一階層
              %li
                = link_to 'メンズ', '#', class: 'main-level'
                %ul.menu__middle-level
                  / 第二階層
                  %li
                    = link_to 'トップス', '#', class: 'child-categories'
                    %ul.menu__small-level
                      / 第三階層
                      %li
                        = link_to 'タンクトップ', '#', class: 'child-categories'
                      %li
                        = link_to 'ノースリーブ', '#', class: 'child-categories'
                      %li
                        = link_to 'チューブトップ', '#', class: 'child-categories'
                  %li
                    = link_to 'ジャケット/アウター', '#', class: 'child-categories'
                    %ul.menu__small-level
                      / 第三階層
                      %li
                        = link_to 'MA-1', '#', class: 'child-categories'
                      %li
                        = link_to 'Flightjacket', '#', class: 'child-categories'
                      %li
                        = link_to 'jacket', '#', class: 'child-categories'
                  -# クリックを無効にした透明なAタグを使い、child_categoryの名前がないところにマウスホバーしても収納されないようになっています。
                  -# child_category_cntに代入すると透明なAタグの大きさがurに合うように変わります。
                  %li{:style => "\n    background: white;\n"}
                    - child_category_cnt = "2"
                    - class_name = "init-right last product#{child_category_cnt}"
                    = link_to '透明Aタグ','#', class: class_name
                    %ul.menu__small-level
                      / 第三階層
              / 第一階層
              %li
                = link_to 'レディース', '#', class: 'main-level'
                %ul.menu__middle-level
                  / 第二階層
                  %li
                    = link_to 'トップス', '#', class: 'child-categories'
                    %ul.menu__small-level
                      / 第三階層
                      %li
                        = link_to 'タンクトップ', '#', class: 'child-categories'
                      %li
                        = link_to 'ノースリーブ', '#', class: 'child-categories'
                      %li
                        = link_to 'チューブトップ', '#', class: 'child-categories'
                  %li
                    = link_to 'ジャケット/アウター', '#', class: 'child-categories'
                    %ul.menu__small-level
                      / 第三階層
                      %li
                        = link_to 'MA-1', '#', class: 'child-categories'
                      %li
                        = link_to 'Flightjacket', '#', class: 'child-categories'
                      %li
                        = link_to '法被', '#', class: 'child-categories'
                  %li
                    = link_to 'パンツ', '#', class: 'child-categories init-right'
                    %ul.menu__small-level
                      / 第三階層
                      %li
                        = link_to 'MA-1', '#', class: 'child-categories'
                      %li
                        = link_to 'Flightjacket', '#', class: 'child-categories'
                      %li
                        = link_to '法被', '#', class: 'child-categories'
                  %li{:style => "\n    background: white;\n"}
                    -products="3"
                    - class_name="init-right last product#{products}"
                    = link_to '透明Aタグ','#', class: class_name
                    %ul.menu__small-level
                      / 第三階層
              / 第一階層
              %li
                = link_to 'カテゴリー一覧', categories_path, class: 'main-level'
          %li.menu__brand-menu
            = link_to '#', class: 'menu__brand-menu__button' do
              %i.fas.fa-tag
              ブランドから探す
            %ul.menu__main-level.brand-height
              / 第一階層
              %li
                = link_to 'シャネル', '#', class: 'main-level'
              / 第一階層
              %li
                = link_to 'ナイキ', '#', class: 'main-level'
              / 第一階層
              %li
                = link_to 'ルイヴィトン', '#', class: 'main-level'
              / 第一階層
              %li
                = link_to 'シュプリーム', '#', class: 'main-level'
              / 第一階層
              %li
                = link_to 'アディダス', '#', class: 'main-level'
              %li
                = link_to 'グッチ', '#', class: 'main-level'
              %li
                = link_to 'ブランド一覧', '#', class: 'main-level'
      .header-lower-right
        %ul.menu
          - if current_user
            %li.menu__notice-menu
              = link_to '#', class: 'menu__notice-menu__button' do
                %i.far.fa-bell
                お知らせ
              %ul.menu__main-level.notice
                / 第一階層
                %li
                  = link_to '#', class: 'main-level noticepack' do
                    .notice-box
                      = image_tag "mercari_profile.png", width: "48", height: "48"  ,class:"notice-img"
                      .text-box
                        《今なら20％還元》メルペイのお支払いで最大P2,000もらえるキャンペーン開催中！
                        %br/
                        %i.far.fa-clock
                        20日前
                        %i.fas.fa-chevron-right
                %li
                  = link_to '#', class: 'main-level noticepack' do
                    .notice-box
                      = image_tag "mercari_profile.png", width: "48", height: "48"  ,class:"notice-img"
                      .text-box
                        《今なら20％還元》メルペイのお支払いで最大P2,000もらえるキャンペーン開催中！
                        %br/
                        %i.far.fa-clock
                        20日前
                        %i.fas.fa-chevron-right.two
            %li.menu__todo-menu.todo-list
              = link_to '#', class: 'menu__todo-menu__button' do
                %i.fas.fa-check
                やることリスト
              %ul.menu__main-level.todo
                / 第一階層
                %li
                  = link_to '#', class: 'main-level noticepack' do
                    .todo-box
                      = image_tag "gray-mercari-icon.png", width: "75", height: "75"  ,class:"todo-img"
                      .text-box
                        現在、やる事リストはありません
            %li.menu__user-menu.user-list
              = link_to mypage_path, class: "menu__user-menu__button" do
                -if current_user.profile.avatar.blank?
                  = image_tag "ねこ２.jpg", width: "30", height: "30", class:"nav-user-profile-img"
                -else
                  = image_tag current_user.profile.avatar.url, width: "30", height: "30", class:"nav-user-profile-img"
                .title-mypage マイページ
              %ul.menu__main-level.user
                / 第一階層
                %li
                  .user-box
                    = image_tag "user_top_background_image.jpg", width: "320", height: "80", class:"user-img"
                    -if current_user.profile.avatar.blank?
                      = image_tag "ねこ２.jpg", width: "60", height: "60", class:"user-profile-img"
                    -else
                      = image_tag current_user.profile.avatar.url, width: "60", height: "60", class:"user-profile-img"
                  = link_to '#', class: 'main-level' do
                    .text-box
                      .user-name
                      - if @current_user.profile.nickname.blank?
                        = @current_user.nickname
                      - else
                        = @current_user.profile.nickname
                      %br/
                      評価: 8 出品数: 0
                .sale-point
                  .sale-point__textbox.clearfix
                    .sale-point__textbox__title
                      売上金
                    .sale-point__textbox__arrow
                      %i.fas.fa-chevron-right
                    .sale-point__textbox__value
                      %n
                      ¥0
                  .sale-point__textbox.clearfix
                    .sale-point__textbox__title
                      ポイント
                    .sale-point__textbox__arrow
                      %i.fas.fa-chevron-right
                    .sale-point__textbox__value
                      %n
                      P0
                .user-nav-products
                  .user-nav-products__product
                    .user-nav-products__product__text
                      = link_to 'いいね!一覧',"#"
                    .user-nav-products__product__arrow
                      %i.fas.fa-chevron-right
                  .user-nav-products__product
                    .user-nav-products__product__text
                      = link_to '出品した商品 - 出品中',"#"
                    .user-nav-products__product__arrow
                      %i.fas.fa-chevron-right
                  .user-nav-products__product
                    .user-nav-products__product__text
                      = link_to '出品した商品 - 取引中',"#"
                    .user-nav-products__product__arrow
                      %i.fas.fa-chevron-right
                  .user-nav-products__product
                    .user-nav-products__products__text__sold
                      = link_to '出品した商品 - 売却済み',"#"
                    .user-nav-products__product__arrow__sold
                      %i.fas.fa-chevron-right
                  .user-nav-products__product
                    .user-nav-products__product__text
                      = link_to '購入した商品 - 取引中',"#"
                    .user-nav-products__product__arrow
                      %i.fas.fa-chevron-right
                  .user-nav-products__product
                    .user-nav-products__product__text
                      = link_to '購入した商品 - 過去の取引',"#"
                    .user-nav-products__product__arrow
                      %i.fas.fa-chevron-right
          - else
            = link_to new_user_path, class: 'menu__signup redbtn' do
              %li
                新規会員登録
            = link_to new_user_session_path, class: 'menu__signin bluebtn' do
              %li
                ログイン
    = breadcrumbs separator: " &rsaquo; "

app/views/shared/_global-only-footer.html.haml
.app-banner
  .app-banner__box
    .app-banner__box__left
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner__box__left__icons
        = image_tag "app-banner-mercari-logo.png", width: "68", height: "68"  ,class:"mercari"
        = image_tag "banner-mercari-info-apple.svg", width: "128", height: "39"  ,class:"apple"
        = image_tag "banner-mercari-info-google-play.svg", width: "128", height: "39"  ,class:"google"
    .app-banner__box__right
      .app-banner__right__image
        = image_tag "app-banner-right.png", width: "300", height: "260"  ,class:"banner-mercari-info-hand-phone"
.global-footer
  .global-footer__upper
    .global-footer__upper__cell.about-mercari
      %h2 メルカリについて
      %ul
        %li= link_to '会社概要(運営会社)',"#"
        %li= link_to '採用情報',"#"
        %li= link_to 'プレスリリース',"#"
        %li= link_to '公式ブログ',"#"
        %li= link_to 'メルカリロゴ利用ガイドライン',"#"
      .global-footer__upper__cell__social-link
        %i.fab.fa-twitter
        &nbsp;  
        %i.fab.fa-facebook-square
    .global-footer__upper__cell.help-guide
      %h2 ヘルプ＆ガイド
      %ul
        %li= link_to 'メルカリガイド',"#"
        %li= link_to 'らくらくメルカリ便',"#"
        %li= link_to 'ゆうゆうメルカリ便',"#"
        %li= link_to '大型メルカリ便',"#"
        %li= link_to '車体取引ガイド',"#"
        %li= link_to 'メルカリあんしん・あんぜん宣言！',"#"
        %li= link_to '偽ブランド品撲滅への取り組み',"#"
        %li= link_to 'メルカリボックス',"#"
    .global-footer__upper__cell.privacy    
      .global-footer__upper__cell
        %h2 プライバシーと利用規約
        %ul
          %li= link_to 'プライバシーポリシー',"#"
          %li= link_to 'メルカリ利用規約',"#"
          %li= link_to 'あんしんスマホサポート制度に関する利用特約',"#"
          %li= link_to 'コンプライアンスポリシー',"#"
      .global-footer__upper__cell
        %h2  
          %br/
        %ul
          %li= link_to '個人データの安全管理に係る基本方針',"#"
          %li= link_to '特定商取引に関する表記',"#"
          %li= link_to '資金決済法に基づく表示',"#"
          %li= link_to '法令遵守と犯罪抑止のために',"#"
          %li= link_to '返品・返金ポリシー',"#"
    .global-footer__upper__cell.country
      %h2 国
      %ul
        %li= link_to '日本',"#"
        %li= link_to 'United States',"#"
  .global-footer__lower
    = image_tag "footer-white-logo.svg", width: "124", height: "33"  ,class:"google"
    .footer-copylight
      %small © 2019 Mercari

app/views/shared/_global-sell-button.html.haml
= link_to(new_product_path, class:'footer-sell-button') do
  %h2 出品
  %i.fas.fa-camera
  